export const GET_SOLAR_MODULES_REQUEST = "GET_SOLAR_MODULES_REQUEST";
export const GET_SOLAR_MODULES_SUCCESS = "GET_SOLAR_MODULES_SUCCESS";
export const GET_SOLAR_MODULES_FAILED = "GET_SOLAR_MODULES_FAILED";
export const ADD_SOLAR_MODULE_TO_CART = "ADD_SOLAR_MODULE_TO_CART";
export const REMOVE_SOLAR_MODULE_FROM_CART = "REMOVE_SOLAR_MODULE_FROM_CART";
